### ISSUE TITLE
Option to show Unicode BIDI characters (CVE-2021-42574)

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#127]
See https://www.trojansource.codes, it is possible to sneak in Unicode control characters which re-order how source code is understood - and if the editor doesn't show them (none did by default), bad things can happen.

How VScode solved it: https://code.visualstudio.com/updates/v1_62#_unicode-directional-formatting-characters

**Comment by gamecreature** [comment]
Source code sample

https://github.com/microsoft/vscode/pull/136347/commits/d2c24cc1d1161193c46ac44364a053c082657d69


Finding these character isn't very hard. I to figure out how to renderer it.
The render pipeline uses QTextLayout to render this stuff, I don't know if I can render several characters as one characters.

Btw I tried the 'bad' code in Edbee.. The cursor behaves very strange when move past this code. (It move correctly from right to left)

Sample bad code:

```
//              from, to, amount
transferBalance(5678,‮6776,4321‬,"USD");
```

**Comment by gamecreature** [comment]
Work in progress...

![image](https://user-images.githubusercontent.com/577933/140481999-570e4d61-ba40-4319-8c0f-49db9336aa7c.png)

This look good, but isn't working. The caret positioning doesn't respect the [U+202e] texts a single character.
I don't know if this can be resolved easily ..

**Comment by vadi2** [comment]
Does it treat it as multiple characters?

**Comment by gamecreature** [comment]
Yes, that's the problem for now..  Perhaps I will try an alternative for now.
Showing a single error character... (Problem is you don't see the unicode-code)

![image](https://user-images.githubusercontent.com/577933/140483479-57459e26-f64b-4f91-809a-506a9f983a50.png)

**Comment by vadi2** [comment]
I think that is a fine alternative 👍

**Comment by gamecreature** [comment]
@vadi2 Can I enable this feature by default?  (I think you don't want to disable this)

Note to self, for VSCODE style rendering:  

At the moment the x-position of the caret is calculated with a line from  `QTextLayout` and `QTextLine::cursorToX(column)`.
It is only used in source files: It  `TextRenderer.cpp` and `TextEditorRenderer.cpp`

Because the QTextLine contains the full text [U+XXXX] it  will calculate the wrong x-position. Perhaps it is possible to override the QTextLine to offset column location supplied when calculating the x. 

Other note to self:  

Research QTextLayout.setPreeditArea? Is it usable to add pieces text that the cursor skips

**Comment by vadi2** [comment]
I agree, it should be enabled by default.

**Comment by gamecreature** [comment]
Btw the current solution isn't, perfect, it doesn't correctly update the other format-ranges. But I guess is sufficient for now, to improve security related issues 

![image](https://user-images.githubusercontent.com/577933/140488040-07dce132-9828-4377-a8c1-17467e752b7a.png)

**Comment by vadi2** [comment]
What do you mean by the other format ranges? Things like [homoglyphs](https://github.com/nickboucher/trojan-source/blob/main/C%2B%2B/homoglyph-function.cpp)?

**Comment by gamecreature** [comment]
The syntax highlighting is shifted for the line with bidi-characters , because the control character is becoming visibile. (When you look at the example above. The 6 becomes white instead of the comma).

**Comment by vadi2** [comment]
Yeah, I see. Well we'll expose an option to turn it off should anyone actually be working with bidirectional text - which isn't a usecase we have in Mudlet.

**Comment by vadi2** [comment]
Could you add it a as a configurable document option, so we can allow users to change this at runtime?

**Comment by gamecreature** [comment]
I just implement it with a TextEditorConfig::renderBidiContolCharacters (which defaults to true)
Further adopted another character as warning symbol: ␥ (http://unicode.org/charts/PDF/U2400.pdf)
This character influence the caret-movement en syntax coloring.  (So it's much better)

Further this is how it looks with renderBidiContolCharacters = false

![image](https://user-images.githubusercontent.com/577933/140609799-22fc5d4b-1c71-4fab-b799-6a774f26e6cf.png)

And this with renderBidiContolCharacters = true

![image](https://user-images.githubusercontent.com/577933/140609821-a9b73e28-245f-4f03-9e89-d43518155aa0.png)

Also the control characters are disabled, because they are replaced. So the order of the source-code remains.

**Comment by vadi2** [comment]
Great, thanks!
