### ISSUE TITLE
 HOME and END keyboard keys does not work in the editor on OSX

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#146]
HOME and END keyboard keys does not work in the editor on OSX, see https://github.com/Mudlet/Mudlet/issues/4408

**Comment by gamecreature** [comment]
I've just tested this issue in the edbee-app.

HOME and END just work like expected (on OSX)
- Home => Moves to the to start of file
- End => Moves to the to end of file

Home uses the keybinding 'move_to_start_of_document' in `edbee/data/factorykeymap.cpp:31`

```c
add( "goto_bof", "move_to_start_of_document" );
```

Which is converted to the following key sequence in `edbee/models/texteditorkeymap.cpp:285`

```c
h.insert( "move_to_start_of_document", QKeySequence::MoveToStartOfDocument );
```

Which is a normal Qt QKeySequence. <https://doc.qt.io/qt-6/qkeysequence.html#StandardKey-enum>
Is it possible the cause is a custom keymap?

**Comment by rparet** [comment]
Just added a note to https://github.com/Mudlet/Mudlet/issues/4408 but tl;dr I believe this is working as designed.
