### ISSUE TITLE
How to do column selection?

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#28]
The multiple caret selection through ctrl+click works pretty awesome! I can't figure out how to do [column selection](https://www.sublimetext.com/docs/2/column_selection.html) though which is something I find really handy for editing blocks of text. Is it possible?

**Comment by gamecreature** [comment]
On my Mac Ctrl+Shift arrow up/down works to add carets above and below.
(On windows Ctrl+Alt up/down???)
```json
   { "keys": "Ctrl+Alt+Up", "command": "add_caret_prev_line" },
   { "keys": "Ctrl+Alt+Down", "command": "add_caret_next_line" }
```
Middle mouse column selection isn't (yet) implemented. But I guess it is doable

**Comment by vadi2** [comment]
Oh. Those key combinations are used in Linux for switching workspaces and in Windows for changing the screen orientation, so I think by default it only really works on macOS.

I'll have to find out how to change this - I imagine it's related to keymaps?

**Comment by gamecreature** [comment]
What keys do you expect to work? (I want the editor to work on every platform 😉 )
I have a hardcoded fallback keymap in the texteditorkeymap.cpp ..  (can add some more common defaults in there)

And edbee-app uses the edbee-data repos with hash some platform specific keymaps

BTW, linux default in (edbee-data) is:
```json
		{ "keys": "Meta+shift+Up", "command": "add_caret_prev_line" },
		{ "keys": "Meta+shift+Down", "command": "add_caret_next_line" },
```

There isn't a  shortcut in the fallback keymap for this command. 
I think it's great to add it.. So please suggest what kind of key you expect on Linux/Windows

So this needs to be fixed in edbee-lib

**Comment by vadi2** [comment]
Yeah that one worked fine for me actually! Amazing! Where is the list of them?

**Comment by gamecreature** [comment]
You can find the keysmaps supplied by edbee-data here:  https://github.com/edbee/edbee-data/tree/master/keymaps

**Comment by vadi2** [comment]
Aha thanks.

**Comment by SlySven** [comment]
💡  Maybe, for those of us with more than _three_ mouse buttons, there might be other keymodifers/mouseclicks that could be used...
