### ISSUE TITLE
markAll() - slow for many matches

### ISSUE THREAD

**Issue by vadi2** [edbee/edbee-lib#99]
We've got this bit of code that we're using to highlight search matches:

```cpp
    auto controller = mpSourceEditorEdbee->controller();
    auto searcher = controller->textSearcher();
    controller->borderedTextRanges()->clear();
    controller->textSelection()->range(0).clearSelection();
    searcher->setSearchTerm(text);
    searcher->markAll(controller->borderedTextRanges());
    controller->update();
```

And when we use it on say a 1,000 line document [like this](https://github.com/demonnic/EMCO/blob/master/src/scripts/EMCO/EMCO.lua), highlighting a single character like `c` takes a really long while:

![Selection_142](https://user-images.githubusercontent.com/110988/83251301-b9fafc80-a1a9-11ea-9fb1-15c036ec8a63.png)
 
Are we using the API right or is there something that can be done?

We've already disabled highlighting for one or two character searches, but that's more of a workaround than a solution, since VS Code on the same machine handles it okay.

**Comment by gamecreature** [comment]
That does't sound very good. I have to look into this. ( Unfortunately I don't have much time these days for Edbee).

My first impression is that the markAll and searchAll functions are very inefficient, because it uses a 'findNextRange' call for every item searched. 

FindNextRange is a method that can called separately. 
A much better approach would be to use 1 call that uses the regexp just once in a loop.
So an optimised rewrite of markAll  without calling findNextRange would be a solution

Btw. VSCode probably uses threading for searching in the background.

**Comment by gamecreature** [comment]
@vadi2 Could you check if this improves the situation?

**Comment by vadi2** [comment]
We are good on this now, thank you :+1:
